"""updated comment table

Revision ID: 02ca0db90147
Revises: 3dc789ed47b1
Create Date: 2022-01-21 15:35:29.528278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ca0db90147'
down_revision = '3dc789ed47b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'comment_section',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('comment', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('comment', 'comment_section',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
