"""Debugging parent and children comments

Revision ID: b0c084ec161e
Revises: 13e8b43c5fab
Create Date: 2022-01-21 16:10:50.328130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c084ec161e'
down_revision = '13e8b43c5fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('children', sa.Integer(), nullable=True))
    op.drop_constraint('comment_comment_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['children'], ['id'])
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_comment_id_fkey', 'comment', 'comment', ['comment_id'], ['id'])
    op.drop_column('comment', 'children')
    # ### end Alembic commands ###
