"""empty message

Revision ID: fb38801cbe91
Revises: b0c084ec161e
Create Date: 2022-01-22 17:46:25.879457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb38801cbe91'
down_revision = 'b0c084ec161e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_children_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.drop_column('comment', 'children')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('children', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_children_fkey', 'comment', 'comment', ['children'], ['id'])
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
